#ifndef DEVICEGLOBAL_H
#define DEVICEGLOBAL_H

#ifdef BUILD_CLDEVICE_STATIC
#define CLDEVICE_EXPORT
#else
#if defined(BUILD_CLDEVICE_LIB)
#  undef CLDEVICE_EXPORT
#  define CLDEVICE_EXPORT Q_DECL_EXPORT
#else
#  undef CLDEVICE_EXPORT
#  define CLDEVICE_EXPORT Q_DECL_IMPORT //only for vc?
#endif
#endif //BUILD_CLDEVICE_STATIC

#define CL_BEGIN_NAMESPACE namespace cl {
#define CL_END_NAMESPACE }
#define DEVICE_BEGIN_NAMESPACE namespace device::v1 {
#define DEVICE_END_NAMESPACE }

CL_BEGIN_NAMESPACE
DEVICE_BEGIN_NAMESPACE

CLDEVICE_EXPORT void initialize();

DEVICE_END_NAMESPACE
CL_END_NAMESPACE

#endif // DEVICEGLOBAL_H
